### ISSUE TITLE
[jQuery] 从目录进不去，点击目录到另一个目录，作者可以试试

### ISSUE THREAD

**Issue by vipbo** [haizlin/fe-interview#1173]
点击目录，跳转到lib，选择jq到目录，再点击还是lib,循环往复，进不到详情页，作者可以试试

**Comment by vipbo** [comment]
![image](https://user-images.githubusercontent.com/29148689/64500527-1fdbe700-d2f0-11e9-8a36-a1c596de928d.png)

**Comment by haizhilin2013** [comment]
好的，收到，已修复，非常感谢提醒！
