### ISSUE TITLE
[js] 用递归算法实现，数组长度为5且元素的随机数在2-32间不重复的值

### ISSUE THREAD

**Issue by BinghuiXie** [haizlin/fe-interview#1407]
```javascript

function foo(arr) {
        if (arr.length === 5) {
            return arr;
        }
        let num = Math.round(Math.random() * 31 + 2);
        arr.push(num);
        arr = [...new Set(arr)];
        return foo(arr);
    }

```

**Comment by haizhilin2013** [comment]
@BinghuiXie 第一天的题，已经出过了，请在这里作答：#3

**Comment by xgqfrms** [comment]
```js
"use strict";

/**
 * 
 * @author xgqfrms
 * @license MIT
 * @copyright xgqfrms
 * @created 2019-11-14
 * 
 * @description 
 * @augments 
 * @example 
 * @link https://github.com/haizlin/fe-interview#%E8%B5%B7%E6%BA%90
 * 
 */

let log = console.log;

const recursiveFun = (arr = [], len = 5, min = 2, max = 32) => {
    const rand = Math.floor(Math.random() * (max - min) + min);
    if(arr.length < len && !arr.includes(rand)){
        arr.push(rand);
        return recursiveFun(arr);
    } else {
        return arr;
    }
}

const arr = recursiveFun();
log(`random array`, arr);

```

**Comment by haizhilin2013** [comment]
> ```js
> "use strict";
> 
> /**
>  * 
>  * @author xgqfrms
>  * @license MIT
>  * @copyright xgqfrms
>  * @created 2019-11-14
>  * 
>  * @description 
>  * @augments 
>  * @example 
>  * @link https://github.com/haizlin/fe-interview#%E8%B5%B7%E6%BA%90
>  * 
>  */
> 
> let log = console.log;
> 
> const recursiveFun = (arr = [], len = 5, min = 2, max = 32) => {
>     const rand = Math.floor(Math.random() * (max - min) + min);
>     if(arr.length < len && !arr.includes(rand)){
>         arr.push(rand);
>         return recursiveFun(arr);
>     } else {
>         return arr;
>     }
> }
> 
> const arr = recursiveFun();
> log(`random array`, arr);
> ```

https://github.com/haizlin/fe-interview/issues/3
