### ISSUE TITLE
[js] 

### ISSUE THREAD

**Issue by buguan3721** [haizlin/fe-interview#1758]
var arr = [];
function l(min,max,maxLen){
    return function(arr){
        var random =  Math.floor(Math.random() * (max - min + 1)) + min;
        if(!arr.includes(random)){
            arr.push(random);
        }
        if(arr.length >= maxLen) return arr;
        arguments.callee(arr);
    }
}
l(2,32,5)(arr);

**Comment by forever-z-133** [comment]
？？？？ 无题之作？

推荐拆成多个函数更佳。
比如：random，uniquePush，createRandomArray。

其实什么场景下会需要用随机数数组呢，递增 ID 再乱序不香吗。
