### ISSUE TITLE
原型相关[js] 

### ISSUE THREAD

**Issue by CHWYH** [haizlin/fe-interview#2648]
var A = function() {};
var b = new A();
A.prototype = {
    n: 0,
    m: 1
}
与以下方式的声明有什么区别，为什么？
var A = function() {};
var b = new A();
A.prototype.n = 0;
A.prototype.m = 1;

**Comment by haizhilin2013** [comment]
是要出题吗？出题可以在这里提交哦：http://www.h-camel.com/contribution.html

**Comment by CHWYH** [comment]
好的，还以为是直接提交 issue&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haizlin/fe-interview"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月15日(星期三) 中午1:04
收件人:&nbsp;"haizlin/fe-interview"<fe-interview@noreply.github.com&gt;;
抄送:&nbsp;"WYH"<857292988@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [haizlin/fe-interview] 原型相关[js]  (#2648)





 
是要出题吗？出题可以在这里提交哦：http://www.h-camel.com/contribution.html

**Comment by haizhilin2013** [comment]
感谢贡献！那我先关闭这个issues了
