### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by guokangf** [haizlin/fe-interview#2881]
题可以浓缩一下，再有答案就更好了。
只出题，越没人答越没人讨论，可能慢慢就丧失兴趣了

**Comment by haizhilin2013** [comment]
> 题可以浓缩一下，再有答案就更好了。
> 只出题，越没人答越没人讨论，可能慢慢就丧失兴趣了

感谢建议，本项目的宗旨是：勤思考 - 多动手 - 善总结 - 能坚持

至于回不回答，看个人的吧，从第一天开始就没强求过谁！既使没人回答，此项目也会一直会持续下去（至少到1000天），因为我曾经说过，先利已的同时再小带下利他，如不能利他，利已也足已！

**Comment by guokangf** [comment]
> > 题可以浓缩一下，再有答案就更好了。
> > 只出题，越没人答越没人讨论，可能慢慢就丧失兴趣了
> 
> 感谢建议，本项目的宗旨是：勤思考 - 多动手 - 善总结 - 能坚持
> 
> 至于回不回答，看个人的吧，从第一天开始就没强求过谁！既使没人回答，此项目也会一直会持续下去（至少到1000天），因为我曾经说过，先利已的同时再小带下利他，如不能利他，利已也足已！

@haizhilin2013 好的，无论怎么样还是非常感谢此项目🙏🙏🙏
