### ISSUE TITLE
[js] 

### ISSUE THREAD

**Issue by knwceas** [haizlin/fe-interview#3214]
```
function count(str1, str2) {
  let s = 0;
  for (let i = 0; i <= str2.length-str1.length; i++) {
    if (str1 === str2.substring(i, i + str1.length )) s++;
  }  
  return s;
}
```

**Comment by haizhilin2013** [comment]
请在具体题目下答题，非常感谢

**Comment by knwceas** [comment]
抱歉，好的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haizlin/fe-interview"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 晚上6:16
收件人:&nbsp;"haizlin/fe-interview"<fe-interview@noreply.github.com&gt;;
抄送:&nbsp;"左左右右"<2547407546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [haizlin/fe-interview] [js]  (#3214)





 
请在具体题目下答题，非常感谢
