### ISSUE TITLE
【建议】h-camel 网站 OAuth 权限要的太多了

### ISSUE THREAD

**Issue by MoyuScript** [haizlin/fe-interview#4264]
![image](https://user-images.githubusercontent.com/45550579/127435945-57d760c3-3ba4-4b15-8297-0fdd2b390cc7.png)

如图，想注册但是发现要的权限太多了，竟然要对公共仓库读写，建议降低权限要求（仅获取个人公开信息）。

**Comment by haizhilin2013** [comment]
不好意思，这个是github授权登录自带的权限，我刚看了下，没有找到地方可以修改的，这个权限在你授权的时候好像是可以选择的。

**Comment by MoyuScript** [comment]
可以参考这个：https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps

URL 中有个 scope 参数，改成 read:user 就可以了

**Comment by haizhilin2013** [comment]
好勒，感谢，我有时间修改下
