### ISSUE TITLE
[js] 第一题

### ISSUE THREAD

**Issue by 1596944197** [haizlin/fe-interview#4968]
`
`
function randomArr(set = new Set) {
  if (set.size === 5) return [...set]
  let len = set.size
  while (len === set.size) {
    set.add(rand())
  }
  return randomArr(set)

  function rand() {
    let value = +(Math.random() * 32).toFixed(0)
    return value >= 2 ? value : rand()
  }
}

**Comment by haizhilin2013** [comment]
请在某一题的下方回答，不需要重新开新的issues
